// Autogenerated with StateSmith 0.0.0-local-build+7256781d3d300d3fdb270ca273ad3d157c75b0e0.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#include "MySm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
// #include "your_header_here.h"
    

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(MySm* sm, MySm_StateId desired_state);

static void ROOT_enter(MySm* sm);

static void STATE_1_enter(MySm* sm);

static void STATE_1_exit(MySm* sm);

static void STATE_1_do(MySm* sm);

static void STATE_1_help(MySm* sm);

static void STATE_2_enter(MySm* sm);

static void STATE_2_exit(MySm* sm);

static void STATE_2_do(MySm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void MySm_ctor(MySm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void MySm_start(MySm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(STATE_1)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `STATE_1`.
            STATE_1_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void MySm_dispatch_event(MySm* sm, MySm_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: MySm
        case MySm_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: STATE_1
        case MySm_StateId_STATE_1:
            switch (event_id)
            {
                case MySm_EventId_DO: STATE_1_do(sm); break;
                case MySm_EventId_HELP: STATE_1_help(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: STATE_2
        case MySm_StateId_STATE_2:
            switch (event_id)
            {
                case MySm_EventId_DO: STATE_2_do(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(MySm* sm, MySm_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case MySm_StateId_STATE_1: STATE_1_exit(sm); break;
            
            case MySm_StateId_STATE_2: STATE_2_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(MySm* sm)
{
    sm->state_id = MySm_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_1
////////////////////////////////////////////////////////////////////////////////

static void STATE_1_enter(MySm* sm)
{
    sm->state_id = MySm_StateId_STATE_1;
    
    // STATE_1 behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_1
}

static void STATE_1_exit(MySm* sm)
{
    // STATE_1 behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_1
    
    sm->state_id = MySm_StateId_ROOT;
}

static void STATE_1_do(MySm* sm)
{
    // STATE_1 behavior
    // uml: do
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_1
    
    // No ancestor handles this event.
}

static void STATE_1_help(MySm* sm)
{
    // STATE_1 behavior
    // uml: help TransitionTo(STATE_2)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        STATE_1_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `STATE_2`.
        STATE_2_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for STATE_1
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_2
////////////////////////////////////////////////////////////////////////////////

static void STATE_2_enter(MySm* sm)
{
    sm->state_id = MySm_StateId_STATE_2;
    
    // STATE_2 behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_2
}

static void STATE_2_exit(MySm* sm)
{
    // STATE_2 behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_2
    
    sm->state_id = MySm_StateId_ROOT;
}

static void STATE_2_do(MySm* sm)
{
    // STATE_2 behavior
    // uml: do
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_2
    
    // No ancestor handles this event.
}

// Thread safe.
char const * MySm_state_id_to_string(MySm_StateId id)
{
    switch (id)
    {
        case MySm_StateId_ROOT: return "ROOT";
        case MySm_StateId_STATE_1: return "STATE_1";
        case MySm_StateId_STATE_2: return "STATE_2";
        default: return "?";
    }
}

// Thread safe.
char const * MySm_event_id_to_string(MySm_EventId id)
{
    switch (id)
    {
        case MySm_EventId_DO: return "DO";
        case MySm_EventId_HELP: return "HELP";
        default: return "?";
    }
}
