// Autogenerated with StateSmith 0.0.0-local-build+7256781d3d300d3fdb270ca273ad3d157c75b0e0.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Tag Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#include "TagSm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
// #include "your_header_here.h"
    

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(TagSm* sm, TagSm_StateId desired_state);

static void ROOT_enter(TagSm* sm);

static void STATE_13_enter(TagSm* sm);

static void STATE_13_exit(TagSm* sm);

static void STATE_13_do(TagSm* sm);

static void STATE_13_getit(TagSm* sm);

static void STATE_21_enter(TagSm* sm);

static void STATE_21_exit(TagSm* sm);

static void STATE_21_do(TagSm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TagSm_ctor(TagSm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TagSm_start(TagSm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(STATE_13)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `STATE_13`.
            STATE_13_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TagSm_dispatch_event(TagSm* sm, TagSm_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: TagSm
        case TagSm_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: STATE_13
        case TagSm_StateId_STATE_13:
            switch (event_id)
            {
                case TagSm_EventId_DO: STATE_13_do(sm); break;
                case TagSm_EventId_GETIT: STATE_13_getit(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: STATE_21
        case TagSm_StateId_STATE_21:
            switch (event_id)
            {
                case TagSm_EventId_DO: STATE_21_do(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(TagSm* sm, TagSm_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case TagSm_StateId_STATE_13: STATE_13_exit(sm); break;
            
            case TagSm_StateId_STATE_21: STATE_21_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(TagSm* sm)
{
    sm->state_id = TagSm_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_13
////////////////////////////////////////////////////////////////////////////////

static void STATE_13_enter(TagSm* sm)
{
    sm->state_id = TagSm_StateId_STATE_13;
    
    // STATE_13 behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_13
}

static void STATE_13_exit(TagSm* sm)
{
    // STATE_13 behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_13
    
    sm->state_id = TagSm_StateId_ROOT;
}

static void STATE_13_do(TagSm* sm)
{
    // STATE_13 behavior
    // uml: do
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_13
    
    // No ancestor handles this event.
}

static void STATE_13_getit(TagSm* sm)
{
    // STATE_13 behavior
    // uml: getit TransitionTo(STATE_21)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        STATE_13_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `STATE_21`.
        STATE_21_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for STATE_13
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATE_21
////////////////////////////////////////////////////////////////////////////////

static void STATE_21_enter(TagSm* sm)
{
    sm->state_id = TagSm_StateId_STATE_21;
    
    // STATE_21 behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_21
}

static void STATE_21_exit(TagSm* sm)
{
    // STATE_21 behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_21
    
    sm->state_id = TagSm_StateId_ROOT;
}

static void STATE_21_do(TagSm* sm)
{
    // STATE_21 behavior
    // uml: do
    {
        // Step 1: execute action ``
    } // end of behavior for STATE_21
    
    // No ancestor handles this event.
}

// Thread safe.
char const * TagSm_state_id_to_string(TagSm_StateId id)
{
    switch (id)
    {
        case TagSm_StateId_ROOT: return "ROOT";
        case TagSm_StateId_STATE_13: return "STATE_13";
        case TagSm_StateId_STATE_21: return "STATE_21";
        default: return "?";
    }
}

// Thread safe.
char const * TagSm_event_id_to_string(TagSm_EventId id)
{
    switch (id)
    {
        case TagSm_EventId_DO: return "DO";
        case TagSm_EventId_GETIT: return "GETIT";
        default: return "?";
    }
}
