// Autogenerated with StateSmith 0.0.0-local-build+7256781d3d300d3fdb270ca273ad3d157c75b0e0.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Tag Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var
#include "radio_wrap.h"
#include "Tag.h"
#include "Timers.h"
#include "main.h"



typedef enum TagSm_EventId
{
    TagSm_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    TagSm_EventId_GETIT = 1,
    TagSm_EventId_HELP = 2
} TagSm_EventId;

enum
{
    TagSm_EventIdCount = 3
};

typedef enum TagSm_StateId
{
    TagSm_StateId_ROOT = 0,
    TagSm_StateId_STATE_13 = 1,
    TagSm_StateId_STATE_21 = 2
} TagSm_StateId;

enum
{
    TagSm_StateIdCount = 3
};


// Generated state machine
// forward declaration
typedef struct TagSm TagSm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct TagSm_Vars
{
    uint32_t count; // this var can be referenced in diagram
    uint32_t FirstPkt; // Flag to record if the role has a first packet
} TagSm_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TagSm_ctor(TagSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TagSm_start(TagSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TagSm_dispatch_event(TagSm* sm, TagSm_EventId event_id);

// Thread safe.
char const * TagSm_state_id_to_string(TagSm_StateId id);

// Thread safe.
char const * TagSm_event_id_to_string(TagSm_EventId id);

// Generated state machine
struct TagSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    TagSm_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    TagSm_Vars vars;
};

